package com.jurjandreigeorge.defroster.domain

val welcomeTexts = listOf(
    "When snow can’t melt fast enough",
    "Melt snow at high speed",
    "Fast track from ice age to global warming",
    "Getting hot, one snowflake at a time",
    "Turning Arctic expeditions into summer strolls",
    "For when glaciers just don’t thaw fast enough",
    "Ice doesn’t stand a chance against this bad boy",
    "The snowstorm’s worst nightmare",
    "Where winter surrenders in seconds",
    "Turning frost into fuel since forever",
    "Because sometimes snow needs a little boost to vanish",
    "Makes your heartbeat pick up speed",
    "For when winter’s too slow to get with the program",
    "When snow needs a high-velocity exit",
    "Snowflakes can’t keep up with this kind of speed",
    "No ice can keep up with this level of efficiency",
    "For snow that’s running out of time",
    "Who doesn’t need a little climate change",
    "Because slow snowmelt is so last century",
    "Turning cold into hot at record-breaking speed",
    "More effective than climate change",
    "When ice realizes it’s on borrowed time",
    "Where snowflakes go to retire",
    "The silent partner in every race to defrost",
    "It’s not weather control, but it sure feels like it",
    "The only thing faster than this heat is light",
    "Making winter take a permanent vacation",
    "Melting the competition—and everything else in its way",
    "The only high here is the temperature",
    "Giving frost the kind of rush it never saw coming",
    "Not illegal, just highly effective at melting",
    "Turning chill vibes into fast-forward heatwaves",
    "The heater that turns sub-zero into zero chill",
    "When frost needs an intervention, this steps in",
    "Snowflakes don’t just melt—they sprint out of here",
    "A heater so fast, even glaciers would call it overkill",
    "When melting snow isn’t just a process—it’s a lifestyle",
    "Turns snow into water so fast, even it needs a breather",
    "For frost that needs to speed its way out of existence",
    "Snowflakes check in, steam races out—no chill, all thrill",
    "Melting snow so fast, it should come with a disclaimer",
    "Ice doesn’t just melt—it straight-up vanishes at this speed",
    "Taking frost from zero to gone faster than you can say ‘faster’",
    "This heater doesn’t just warm—it elevates",
    "For frost that needs to feel the rush of instant change",
    "The only thing getting high here is the temperature gauge",
    "When ice needs a quick pick-me-up, this delivers",
    "Turning cold into hot like it’s chasing the ultimate high",
    "Heating things up faster than a caffeine addiction",
    "Heat levels so intense, even snow gets a contact high"
)